### ISSUE TITLE
Feature - recursive imports

### ISSUE THREAD

**Issue by routters** [deprint/build-tools-ant#2]
Hi, thanks for making this tool.  I find it incredibly useful!

Some of the `build.xml` files that I use reference other files by means of [import](https://ant.apache.org/manual/Tasks/import.html) statements.  For example, `build.xml` might have this statement as one of its lines:
```xml
<import file="more.targets/build.config.xml"/>
```

When I run ant at the command line, using the main `build.xml` file, it is able to run these imported targets without having to add anything extra to the command.  For example, the file `more.targets/build.config.xml` might have a target of `imported.config.target` somewhere within it.  These commands still run successfully from the command line:
```bash
ant -buildfile build.xml imported.config.target
```
or even
```bash
ant imported.config.target
```

Could you please update the build-tools-ant code so that it recursively pulls in these imported targets as build-tools commands?  If it is difficult or somehow inadvisable to create a fully recursive solution, then a solution that simply pulls in targets from the first level of import statements would still be very helpful.

**Comment by fstiewitz** [comment]
This package is due to a rewrite anyway since it's using regular expressions (edit: actually it uses a xml parser but it's still hacked together) for parsing the build file.
It looks like there is a `ant -p` (?) command which prints a target list instead of executing anything. I never worked with imports before but if that list also includes imported targets then the implementation should be fairly straightforward.

**Comment by fstiewitz** [comment]
`v0.1.3` is online and should work.

**Comment by routters** [comment]
Thanks for the quick turnaround!  The new code reads in the additional targets from the imported files.
